### ISSUE TITLE
Team Geek ―Googleのギークたちはいかにしてチームを作るのか

### ISSUE THREAD

**Issue by nori3636** [nori3636/Bookshelf#1]
著者：Brian W. Fitzpatrick, Ben Collins-Sussman
出版社 ‏ : ‎ オライリージャパン (2013/7/20)
発売日 ‏ : ‎ 2013/7/20

https://www.amazon.co.jp/dp/4873116309

**Comment by norikmb** [comment]
読みました。
人間にフォーカスしているのと、よくSNS等で言及されていることがまとまってるように感じた。
声掛けの仕方、レビューの際に自分の疑問を解決するように行うというのはすぐ実践できそうなのでやってみたい
